version: '3.8'

services:
  postgres:
    container_name: nest-api-loja
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: loja
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
